In [1]:
import numpy as np


In [2]:
l1 =[1,2,3]
v1 = np.array([10,20,5])
v2 = np.array([5,5,10])
print(v1.dot(v2))
print(v2)

200
[ 5  5 10]


In [8]:
l1 =[1,2,3]
v1 = np.array([10,20,5])
print(v1.ndim) # property function
print(v1.shape)


1
(3,)


In [3]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m1)
print("=================")
m2 = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
print(m2)
print("=================")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
class student:
    def __init__(self,name):
        self.name =name
    def get_info (self):
        return f"my name is{self.name}"
    

           


In [ ]:
s1

In [10]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(m1.ndim)
print(m1.shape)

2
(3, 3)


In [11]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
def 

In [16]:
vec = np.array([1,
                2,
                3,
                4])
#(4,) means 4 raws and 1 colomn
vec.shape
vec.shape[0]

4